import { Router, type IRouter } from "express";

const router: IRouter = Router();

const rcaDetails = [
  {
    id: "RCA-301",
    incidentTitle: "Redshift connection pool exhaustion",
    pipeline: "fin_gl_ledger_sync",
    rcaStatus: "In Progress",
    daysOpen: 2,
    actionItems: 4,
    completedActions: 1,
    severity: "P1",
    domain: "Finance",
    detectedAt: "2026-04-14T08:25:00Z",
    resolvedAt: null,
    fixedBy: null,
    rootCause: "Redshift connection pool exhausted during peak batch window (08:00–09:00 UTC). 47 concurrent jobs competed for 20 available connections, causing all new connections to be rejected.",
    contributingFactors: ["No connection pool sizing review after Q1 pipeline additions", "Missing circuit breaker on batch scheduler", "Alerting threshold set at 95% (too late)"],
    bugFixDescription: null,
    resolution: null,
    affectedIncidents: ["INC-1042"],
    actionItemsList: [
      { id: 1, description: "Increase Redshift connection pool from 20 to 60", status: "Completed", assignee: "Sarah Chen" },
      { id: 2, description: "Add circuit breaker with backoff on connection failures", status: "In Progress", assignee: "Sarah Chen" },
      { id: 3, description: "Lower alerting threshold from 95% to 75% utilization", status: "Pending", assignee: "Platform Team" },
      { id: 4, description: "Stagger batch job start times in peak window", status: "Pending", assignee: "Scheduling Team" },
    ],
    postMortemUrl: null,
    changeCorrelated: null,
  },
  {
    id: "RCA-298",
    incidentTitle: "OOM on large inventory batch",
    pipeline: "ops_inventory_load",
    rcaStatus: "Pending Review",
    daysOpen: 5,
    actionItems: 3,
    completedActions: 3,
    severity: "P1",
    domain: "Operations",
    detectedAt: "2026-04-09T06:32:00Z",
    resolvedAt: "2026-04-11T14:00:00Z",
    fixedBy: "Priya Patel",
    rootCause: "Inventory batch job attempted to load 4.2M records in a single Spark partition due to missing partition key on the source table after a schema change on April 8th. This caused the executor JVM to exceed its 16GB heap limit.",
    contributingFactors: ["Schema change was not communicated to the pipeline team", "No partition size guard in the ingestion job", "Test environment only validated with 200K records"],
    bugFixDescription: "Added dynamic partition detection: job now checks partition count before execution and auto-splits when estimated record count exceeds 2M. Added schema change notification hook to alert pipeline owners via Slack on DDL changes.",
    resolution: "Deployed hotfix v2.3.1 to production on April 11. Backfill of April 9–10 records completed successfully. Schema change notification framework added to CI/CD pipeline.",
    affectedIncidents: ["INC-1041"],
    actionItemsList: [
      { id: 1, description: "Add auto-partition splitting for batches > 2M records", status: "Completed", assignee: "Priya Patel" },
      { id: 2, description: "Add schema change notification to pipeline owners", status: "Completed", assignee: "Platform Team" },
      { id: 3, description: "Update load test suite to include 5M+ record scenarios", status: "Completed", assignee: "QA Team" },
    ],
    postMortemUrl: "https://wiki.internal/rca/RCA-298",
    changeCorrelated: "Schema change on ops_inventory table — April 8, 2026",
  },
  {
    id: "RCA-295",
    incidentTitle: "Schema drift in campaign data",
    pipeline: "mkt_campaign_agg",
    rcaStatus: "In Progress",
    daysOpen: 3,
    actionItems: 5,
    completedActions: 2,
    severity: "P2",
    domain: "Marketing",
    detectedAt: "2026-04-11T07:50:00Z",
    resolvedAt: null,
    fixedBy: null,
    rootCause: "Upstream marketing platform API v3.2 added two new nullable columns to the campaign events payload. The pipeline's strict schema validation rejected the new fields, causing all aggregation runs to fail at the schema check step.",
    contributingFactors: ["No API version pinning on upstream contract", "Schema registry not enforced on source API", "No canary validation step in pipeline"],
    bugFixDescription: null,
    resolution: null,
    affectedIncidents: ["INC-1040"],
    actionItemsList: [
      { id: 1, description: "Pin upstream API to v3.1 as temporary workaround", status: "Completed", assignee: "Mike Torres" },
      { id: 2, description: "Update schema to accept new nullable fields in v3.2", status: "Completed", assignee: "Mike Torres" },
      { id: 3, description: "Implement schema registry enforcement", status: "In Progress", assignee: "Platform Team" },
      { id: 4, description: "Add canary validation step to catch schema drift early", status: "Pending", assignee: "Data Engineering" },
      { id: 5, description: "Require API versioning contract for all upstream integrations", status: "Pending", assignee: "Architecture Board" },
    ],
    postMortemUrl: null,
    changeCorrelated: "Marketing platform API upgrade to v3.2 — April 10, 2026",
  },
  {
    id: "RCA-290",
    incidentTitle: "S3 permission change broke pipeline",
    pipeline: "hr_payroll_calc",
    rcaStatus: "Completed",
    daysOpen: 8,
    actionItems: 3,
    completedActions: 3,
    severity: "P2",
    domain: "HR",
    detectedAt: "2026-04-06T02:48:00Z",
    resolvedAt: "2026-04-08T11:30:00Z",
    fixedBy: "David Lee",
    rootCause: "Security team rotation of IAM role credentials for the S3 data lake bucket was applied without prior notification to pipeline teams. The HR payroll pipeline's assumed role lost GetObject permissions on the hr-data-lake-prod bucket.",
    contributingFactors: ["No change freeze window for critical pipelines", "IAM credential rotation process lacked automated pipeline notification", "Manual rotation procedure skipped pipeline-owner communication step"],
    bugFixDescription: "Restored IAM role permissions immediately via emergency access request. Long-term fix: integrated IAM change events with PagerDuty notification to all affected pipeline owners. Added automated permission validation step to pipeline startup sequence that checks S3 access before processing begins.",
    resolution: "IAM permissions restored within 2 hours of detection. Automated permission check added to pipeline health probe. IAM rotation runbook updated to require pipeline team sign-off. Post-mortem published and circulated to all data engineering teams.",
    affectedIncidents: ["INC-1035"],
    actionItemsList: [
      { id: 1, description: "Restore IAM GetObject permission for hr-data-lake-prod", status: "Completed", assignee: "David Lee" },
      { id: 2, description: "Add S3 permission health check to pipeline startup", status: "Completed", assignee: "David Lee" },
      { id: 3, description: "Update IAM rotation runbook with pipeline team notification requirement", status: "Completed", assignee: "Security Team" },
    ],
    postMortemUrl: "https://wiki.internal/rca/RCA-290",
    changeCorrelated: "IAM credential rotation — April 5, 2026",
  },
  {
    id: "RCA-288",
    incidentTitle: "Upstream API rate limiting",
    pipeline: "sc_shipment_tracker",
    rcaStatus: "In Progress",
    daysOpen: 4,
    actionItems: 4,
    completedActions: 2,
    severity: "P2",
    domain: "Supply Chain",
    detectedAt: "2026-04-10T04:05:00Z",
    resolvedAt: null,
    fixedBy: null,
    rootCause: "Third-party logistics API (ShipStream v2) lowered rate limits from 500 req/min to 100 req/min without advance notice. The shipment tracker pipeline was issuing 420 req/min during its data pull window, causing 429 errors.",
    contributingFactors: ["No SLA or notification agreement with logistics API vendor", "Pipeline lacked exponential backoff on 429 responses", "No rate limit monitoring on outbound API calls"],
    bugFixDescription: null,
    resolution: null,
    affectedIncidents: ["INC-1036"],
    actionItemsList: [
      { id: 1, description: "Add exponential backoff with jitter on 429 responses", status: "Completed", assignee: "Lisa Park" },
      { id: 2, description: "Reduce outbound request rate to 80 req/min (below 100 limit)", status: "Completed", assignee: "Lisa Park" },
      { id: 3, description: "Negotiate rate limit SLA with ShipStream vendor", status: "In Progress", assignee: "Vendor Management" },
      { id: 4, description: "Add outbound API rate metrics to observability dashboard", status: "Pending", assignee: "Platform Team" },
    ],
    postMortemUrl: null,
    changeCorrelated: "ShipStream API rate limit change — April 9, 2026",
  },
  {
    id: "RCA-285",
    incidentTitle: "Memory leak in churn model",
    pipeline: "cust_churn_predictor",
    rcaStatus: "Open",
    daysOpen: 6,
    actionItems: 0,
    completedActions: 0,
    severity: "P2",
    domain: "Customer",
    detectedAt: "2026-04-08T03:20:00Z",
    resolvedAt: null,
    fixedBy: null,
    rootCause: "Under investigation. Initial evidence points to a memory leak in the scikit-learn model serialization step when processing customer segment batches > 500K records. Heap dumps show accumulating ModelMetadata objects not being garbage collected.",
    contributingFactors: [],
    bugFixDescription: null,
    resolution: null,
    affectedIncidents: ["INC-1038"],
    actionItemsList: [],
    postMortemUrl: null,
    changeCorrelated: "ML model version upgrade to v4.2.0 — April 7, 2026 (suspected)",
  },
  {
    id: "RCA-280",
    incidentTitle: "Data quality regression in AR aging",
    pipeline: "fin_ar_aging_report",
    rcaStatus: "Completed",
    daysOpen: 12,
    actionItems: 5,
    completedActions: 5,
    severity: "P2",
    domain: "Finance",
    detectedAt: "2026-04-02T05:20:00Z",
    resolvedAt: "2026-04-06T16:00:00Z",
    fixedBy: "James Wilson",
    rootCause: "A data transformation bug introduced in release 1.8.4 incorrectly applied a 30-day aging bucket filter to all records instead of only those in the 30–60 day range. This caused approximately 2,400 accounts receivable records to be misclassified in downstream reports.",
    contributingFactors: ["Code review missed edge case in bucket boundary logic", "No data quality assertion on output bucket distributions", "Staging test dataset did not include mixed-bucket records"],
    bugFixDescription: "Fixed the bucket filter logic in `transform_aging_buckets()` — corrected from `days > 30` to `30 < days <= 60`. Added three new data quality assertions to the pipeline: (1) bucket count must sum to total record count, (2) no record may appear in multiple buckets, (3) distribution must fall within 20% of 30-day rolling average. Also added a dedicated integration test using a synthetic dataset covering all bucket boundary conditions.",
    resolution: "Hotfix v1.8.5 deployed April 6. Full backfill of affected records for April 2–5 completed and validated by Finance team. Post-mortem published. Finance stakeholders notified of corrected figures. No regulatory impact identified.",
    affectedIncidents: ["INC-1039"],
    actionItemsList: [
      { id: 1, description: "Fix bucket filter logic in transform_aging_buckets()", status: "Completed", assignee: "James Wilson" },
      { id: 2, description: "Add data quality assertions on output bucket distributions", status: "Completed", assignee: "James Wilson" },
      { id: 3, description: "Add integration test for all bucket boundary conditions", status: "Completed", assignee: "QA Team" },
      { id: 4, description: "Backfill and validate records for Apr 2–5", status: "Completed", assignee: "James Wilson" },
      { id: 5, description: "Notify Finance stakeholders and update reporting", status: "Completed", assignee: "Finance Ops" },
    ],
    postMortemUrl: "https://wiki.internal/rca/RCA-280",
    changeCorrelated: "Release 1.8.4 deployment — April 1, 2026",
  },
  {
    id: "RCA-275",
    incidentTitle: "Treasury rate feed timeout causing stale data",
    pipeline: "fin_treasury_rates",
    rcaStatus: "Completed",
    daysOpen: 10,
    actionItems: 4,
    completedActions: 4,
    severity: "P1",
    domain: "Finance",
    detectedAt: "2026-04-04T07:00:00Z",
    resolvedAt: "2026-04-07T09:00:00Z",
    fixedBy: "Sarah Chen",
    rootCause: "The external Reuters treasury rate API introduced a mandatory TLS 1.3 upgrade requirement on April 3rd. The pipeline's HTTP client was configured with TLS 1.2 max, causing all connections to silently time out rather than fail with a clear error.",
    contributingFactors: ["No TLS version negotiation logging in HTTP client", "API vendor did not send advance notice of TLS requirement change", "Connection timeout (60s) masked the root cause in initial triage"],
    bugFixDescription: "Updated HTTP client configuration to enable TLS 1.3 support. Added explicit TLS handshake error logging to distinguish TLS failures from network timeouts. Implemented a synthetic monitor that tests the API connection every 5 minutes and alerts on handshake failures.",
    resolution: "TLS 1.3 upgrade applied to all pipeline HTTP clients in hotfix v2.1.2. Stale treasury rate data from Apr 4–6 was backfilled using Reuters historical feed. Downstream FX calculation jobs rerun successfully. Post-mortem published.",
    affectedIncidents: ["INC-1033"],
    actionItemsList: [
      { id: 1, description: "Upgrade HTTP client TLS version to support TLS 1.3", status: "Completed", assignee: "Sarah Chen" },
      { id: 2, description: "Add TLS handshake failure logging to HTTP client", status: "Completed", assignee: "Sarah Chen" },
      { id: 3, description: "Add synthetic API connectivity monitor (5-min interval)", status: "Completed", assignee: "Platform Team" },
      { id: 4, description: "Backfill stale treasury rate data for Apr 4–6", status: "Completed", assignee: "Finance Ops" },
    ],
    postMortemUrl: "https://wiki.internal/rca/RCA-275",
    changeCorrelated: "Reuters API TLS 1.3 enforcement — April 3, 2026",
  },
];

router.get("/rca/lifecycle", async (_req, res): Promise<void> => {
  res.json(rcaDetails.map(({ id, incidentTitle, pipeline, rcaStatus, daysOpen, actionItems, completedActions }) => ({
    id, incidentTitle, pipeline, rcaStatus, daysOpen, actionItems, completedActions,
  })));
});

router.get("/rca/detail/:id", async (req, res): Promise<void> => {
  const detail = rcaDetails.find((r) => r.id === req.params.id);
  if (!detail) {
    res.status(404).json({ error: "RCA not found" });
    return;
  }
  res.json(detail);
});

router.get("/rca/repeat-incidents", async (_req, res): Promise<void> => {
  res.json([
    { pipeline: "fin_gl_ledger_sync", count: 7, lastOccurrence: "2026-04-14T08:25:00Z", pattern: "Connection pool exhaustion during peak" },
    { pipeline: "ops_inventory_load", count: 5, lastOccurrence: "2026-04-14T06:32:00Z", pattern: "OOM on batch sizes > 2M records" },
    { pipeline: "sc_shipment_tracker", count: 4, lastOccurrence: "2026-04-14T04:05:00Z", pattern: "Upstream API rate limiting" },
    { pipeline: "mkt_campaign_agg", count: 3, lastOccurrence: "2026-04-14T07:50:00Z", pattern: "Schema validation failure after source changes" },
    { pipeline: "cust_churn_predictor", count: 3, lastOccurrence: "2026-04-14T03:20:00Z", pattern: "Resource exhaustion on model training step" },
  ]);
});

router.get("/rca/failure-patterns", async (_req, res): Promise<void> => {
  res.json([
    { pattern: "ConnectionTimeout", occurrences: 34, affectedPipelines: 8, lastSeen: "2026-04-14T08:23:00Z", trend: "increasing" },
    { pattern: "OutOfMemory", occurrences: 18, affectedPipelines: 5, lastSeen: "2026-04-14T06:30:00Z", trend: "stable" },
    { pattern: "SchemaValidation", occurrences: 15, affectedPipelines: 6, lastSeen: "2026-04-14T07:45:00Z", trend: "increasing" },
    { pattern: "DataQuality", occurrences: 12, affectedPipelines: 4, lastSeen: "2026-04-14T05:15:00Z", trend: "decreasing" },
    { pattern: "PermissionDenied", occurrences: 8, affectedPipelines: 3, lastSeen: "2026-04-14T02:45:00Z", trend: "stable" },
    { pattern: "UpstreamUnavailable", occurrences: 7, affectedPipelines: 4, lastSeen: "2026-04-14T04:02:00Z", trend: "increasing" },
    { pattern: "ResourceExhausted", occurrences: 5, affectedPipelines: 2, lastSeen: "2026-04-14T03:18:00Z", trend: "stable" },
  ]);
});

router.get("/rca/metrics", async (_req, res): Promise<void> => {
  res.json({
    automationSuccessRate: 78.5,
    runbookUsagePercent: 64.2,
    openRcaBacklog: 12,
    avgRcaCompletionDays: 6.8,
    changeCorrelationPercent: 42.0,
  });
});

export default router;
