from __future__ import annotations
from typing import Literal, Optional
from pydantic import BaseModel, Field

class LogAnalysisRequest(BaseModel):
    logText: str = Field(..., description="Raw CloudWatch log text to analyze.")
    jobId: Optional[str] = Field(None, description="Glue job run ID, when available.")
    jobName: Optional[str] = Field(None, description="Glue job name or Lambda function name.")
    resourceType: Literal["job", "lambda"] = Field(..., description="Type of CloudWatch resource.")


class LogAnalysisResponse(BaseModel):
    summary: str = Field(..., description="AI-generated summary of the log.")
    rca: Optional[str] = Field(None, description="RCA generated by the Hugging Face agent.")
    insights: Optional[str] = Field(None, description="Additional notes or findings from the analysis.")
    model: Optional[str] = Field(None, description="Hugging Face model used for the analysis.")


class JiraTicketRequest(BaseModel):
    summary: Optional[str] = Field(None, description="Optional issue summary/title.")
    description: str = Field(..., description="Detailed issue description, typically including log context.")
    rca: Optional[str] = Field(None, description="RCA text to include with the Jira ticket.")
    jobId: Optional[str] = Field(None, description="Glue job run ID, when available.")
    jobName: Optional[str] = Field(None, description="Glue job name or Lambda function name.")
    resourceType: Literal["job", "lambda"] = Field(..., description="Type of CloudWatch resource.")
    issueType: Optional[str] = Field(None, description="Jira issue type name, e.g. Bug.")


class JiraTicketResponse(BaseModel):
    issueKey: str = Field(..., description="Created Jira issue key.")
    issueUrl: Optional[str] = Field(None, description="Web URL for the created Jira issue.")
    summary: Optional[str] = Field(None, description="Summary/title of the created Jira issue.")
